# Generated by Django 4.0.3 on 2022-03-09 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('battery', models.IntegerField(default=100)),
                ('sampling', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('next_ping', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('collect_frequency', models.IntegerField(default=300)),
                ('mac', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'this field already exists'}, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=16)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.building')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('isError', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.box')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datatype')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boxes', to='api.room'),
        ),
    ]
