# Generated by Django 4.0.3 on 2022-03-09 22:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_data_box_delete_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('battery', models.IntegerField(default=100)),
                ('sampling', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('next_ping', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('collect_frequency', models.IntegerField(default=300)),
                ('mac', models.CharField(max_length=32)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boxes', to='api.room')),
            ],
        ),
    ]
